// const names = ['clothers', 'Apparel', 'Garments', 'Attire'];

const names = ['clothers', 'Apparel', 'Garments', 'Attire'];

const locations = [
  'Alachua',
  'Baker',
  'Bay',
  'Bradford',
  'Brevard',
  'Broward',
  'Calhoun',
  'Charlotte',
  'Citrus',
  'Clay',
  'Collier',
  'Columbia', //chưa làm được
  'DeSoto',
  'Dixie',
  'Duval',
  'Escambia',
  'Flagler',
  'Franklin',
  'Gadsden',
  'Gilchrist',
  'Glades',
  'Gulf',
  'Hamilton',
  'Hardee',
  'Hendry',
  'Hernando',
  'Highlands',
  'Hillsborough',
  'Holmes',
  'Indian River',
  'Jackson',
  'Jefferson',
  'Lafayette',
  'Lake',
  'Lee',
  'Leon', //chưa được
  'Levy',
  'Liberty',
  'Madison',
  'Manatee',
  'Marion',
  'Martin',
  'Miami-Dade',
  'Monroe',
  'Nassau',
  'Okaloosa',
  'Okeechobee',
  'Orange',
  'Osceola',
  'Palm Beach',
  'Pasco',
  'Pinellas',
  'Polk',
  'Putnam',
  'Santa Rosa',
  'Sarasota',
  'Seminole',
  'St. Johns',
  'St. Lucie',
  'Sumter',
  'Suwannee',
  'Taylor',
  'Union',
  'Volusia',
  'Wakulla',
  'Walton',
  'Washington',
];

const acronymLocation = ['FL'];
module.exports = {
  names,
  locations,
  acronymLocation,
};
