// const names = ['clothers', 'Apparel', 'Garments', 'Attire'];

const names = ['Sports Clubs & Organizations'];

// const names = ["Promotional", "Advertising", "Marketing",];

const locations = [
  'Alachua',
  // 'Baker',
  // 'Bay',
  // 'Bradford',
  // 'Brevard',
  // 'Broward',
  // 'Calhoun',
  // 'Charlotte',
  // 'Citrus',
  // 'Clay',
  // 'Collier',
  // 'Columbia', //chưa làm được
  // 'DeSoto',
  // 'Dixie',
  // 'Duval',
  // 'Escambia',
  // 'Flagler',
  // 'Franklin',
  // 'Gadsden',
  // 'Gilchrist',
  // 'Glades',
  // 'Gulf',
  // 'Hamilton',
  // 'Hardee',
  // 'Hendry',
  // 'Hernando',
  // 'Highlands',
  // 'Hillsborough',
  // 'Holmes',
  // 'Indian River',
  // 'Jackson',
  // 'Jefferson',
  // 'Lafayette',
  // 'Lake',
  // 'Lee',
  // 'Leon', //chưa được
  // 'Levy',
  // 'Liberty',
  // 'Madison',
  // 'Manatee',
  // 'Marion',
  // 'Martin',
  // 'Miami-Dade',
  // 'Monroe',
  // 'Nassau',
  // 'Okaloosa',
  // 'Okeechobee',
  // 'Orange',
  // 'Osceola',
  // 'Palm Beach',
  // 'Pasco',
  // 'Pinellas',
  // 'Polk',
  // 'Putnam',
  // 'Santa Rosa',
  // 'Sarasota',
  // 'Seminole',
  // 'St. Johns',
  // 'St. Lucie',
  // 'Sumter',
  // 'Suwannee',
  // 'Taylor',
  // 'Union',
  // 'Volusia',
  // 'Wakulla',
  // 'Walton',
  // 'Washington',
];

const locationss = [
  'Alachua',
  'Baker',
  'Bay',
  'Bradford',
  'Brevard',
  'Broward',
  'Calhoun',
  'Charlotte',
  'Citrus',
  'Clay',
  'Collier',
  'Columbia',
  'DeSoto',
  'Dixie',
  'Duval',
  'Escambia',
  'Flagler',
  'Franklin',
  'Gadsden',
  'Gilchrist',
  'Glades',
  'Gulf',
  'Hamilton',
  'Hardee',
  'Hendry',
  'Hernando',
  'Highlands',
  'Hillsborough',
  'Holmes',
  'Indian_River',
  'Jackson',
  'Jefferson',
  'Lafayette',
  'Lake',
  'Lee',
  'Leon',
  'Levy',
  'Liberty',
  'Madison',
  'Manatee',
  'Marion',
  'Martin',
  'Miami-Dade',
  'Monroe',
  'Nassau',
  'Okaloosa',
  'Okeechobee',
  'Orange',
  'Osceola',
  'Palm_Beach',
  'Pasco',
  'Pinellas',
  'Polk',
  'Putnam',
  'Santa_Rosa',
  'Sarasota',
  'Seminole',
  'St._Johns',
  'St._Lucie',
  'Sumter',
  'Suwannee',
  'Taylor',
  'Union',
  'Volusia',
  'Wakulla',
  'Walton',
  'Washington',
];
const acronymLocation = ['FL'];
module.exports = {
  names,
  locations,
  locationss,
  acronymLocation,
};
